version: 2

sources:
  - name: erp
    description: Modelo com as tabelas fonte - raw tables
    database: fea24_4 
    schema: raw_northwind
    tables:
      - name: product
        description: Tabela de produtos
      - name: category
        description: Tabela das categorias
      - name: supplier
        description: Tabela dos fornecedores
      - name: region
        description: Tabela das regiões
      - name: territory
        description: Tabela das cidades
        columns:
          - name: regionid
            description: Identificador das regiões
            tests:
              - relationships:
                  field: ID
                  to: ref('region')
      - name: employeeterritory
        description: Tabela da releção entre os funcionários e as cidades
        columns:
          - name: territoryid
            description: Identificador das cidades
            tests:
              - relationships:
                  field: ID
                  to: ref('territory')
      - name: shipper
        description: Tabela das transpotadores
      - name: custumer
        description: Tabela dos clientes
        columns:
          - name: ID
            description: Identificador dos clientes
      - name: employee
        description: Tabela dos funcionários
        columns:
          - name: ID
            description: Identificador dos funcionários
            tests:
              - unique
              - not_null              
      - name: _order_
        description: Tabela dos cabeçalho das ordens de compra
        columns:
          - name: CUSTOMERID
            description: Identificador dos clientes
            tests:
              - relationships:
                  to: ref('ID')
                  field: custumer
          - name: EMPLOYEEID
            description: Identificador dos funcionários
            tests:
              - relationships:
                  field: ID
                  to: ref('employee')
          - name: ID
            description: Identificador das ordens de compra
            tests:
              - unique
              - not_null
      - name: orderdetail
        columns:
          - name: id
            tests:
              - unique
              - not_null
      

      

